#!/bin/bash
#SBATCH --job-name=$name
#SBATCH --account=$account
#SBATCH --partition=$partition
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=$mem
#SBATCH --time=$time
#SBATCH --gres=gpu:1
#SBATCH --dependency=singleton
#SBATCH --mail-type=end
#SBATCH --mail-user=$email

set -e

# ==== Runoff ==========
module purge
module load $runoff_module/$runoff_version
srun runoff "$yaml" > "$out" 2>&1

# ==== Routing ==========
cd "$routing_slurm_dir"
sbatch "$routing_script"
